name: absen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  intl: ^0.19.0
  flutter_beacon: ^0.5.1
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  geolocator: ^12.0.0
  http: ^1.2.2
  dart_jsonwebtoken: ^2.14.1
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  location: ^6.0.2
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
